FROM openjdk:21-slim AS build
COPY . .
RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:21-jre-jammy
RUN echo 'it is test msg'
RUN ls -la

COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENV JAVA_OPTS = "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom"
ENTRYPOINT ["java", "$JAVA_OPTS", "-jar", "app.jar"]