name: Hadolint scan

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Select the Dockerfile to lint'
        required: true
        default: 'Dockerfile.v0'
        type: choice
        options:
          - 'Dockerfile.v0'
          - 'Dockerfile.v0-fixed'
          - 'Dockerfile.v1'
          - 'Dockerfile.v1-fixed'

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Lint Selected Dockerfile
        id: lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./app/${{ github.event.inputs.dockerfile }}
          config: ./app/hadolint-config.yaml
          format: json
          output-file: lint-output-${{ github.event.inputs.dockerfile }}.json
        continue-on-error: true

      - name: Pretty Print JSON Output
        run: |
          cat lint-output-${{ github.event.inputs.dockerfile }}.json | jq '.'
        shell: bash
