name: Trivy
on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Select the Dockerfile to lint'
        required: true
        default: 'Dockerfile.v0'
        type: choice
        options:
          - 'Dockerfile.v1'
          - 'Dockerfile.v1-fixed'
jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Build an image from Dockerfile
        run: |
          docker build app/ -t coffee-jug-demo:${{ github.sha }} -f ./app/${{ github.event.inputs.dockerfile }}
      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: sample
  ScanCIPipeline:
    name: Simple Scan CI Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build app/ -t coffee-jug-demo:${{ github.sha }} -f ./app/${{ github.event.inputs.dockerfile }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'coffee-jug-demo:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  ScanCIPipelineWithConfig:
    name: Scan CI Pipeline with trivy config
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: ./app/trivy-config.yaml

  TarballScanning:
    name: Scanning a tarball
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build a docker image
        run: |
          docker build ./app/ -t coffee-jug-demo:${{ github.sha }} -f ./app/${{ github.event.inputs.dockerfile }}

      - name: Generate tarball from image
        run: |
          docker save -o vuln-image.tar coffee-jug-demo:${{ github.sha }}
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/vuln-image.tar
          severity: 'CRITICAL,HIGH'